version: '3.8'
services:
  mysql-service:
    image: mysql:8.0
    container_name: my_sql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    ports:
      - 3307:3306
    restart: always

  eureka-server:
    build: ./backend/eureka-server/
    container_name: eureka_container
    ports:
      - 8761:8761
    networks:
      - public
    restart: always
    
  microserviceapp:
    build: ./backend/backend-micro-servce/
    container_name: micro_container
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - 9090:9090
     depends_on:
      - mysql-service
      - eureka-server
    restart: always
  react-js-service:
    build: ./frontend/frontend-app/
    container_name: reactjs-container
    ports:
      - 80:80
    